import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Plus_Jakarta_Sans, Playfair_Display } from 'next/font/google'
import './globals.css'
import { Footer } from '@/components/landing/Footer'
import { OrganizationJsonLd, SoftwareApplicationJsonLd } from '@/components/seo/JsonLd'
import { SupportWidget } from '@/components/support/SupportWidget'
import { AuthModalProvider } from '@/components/auth/AuthModal'

const satoshi = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  variable: '--font-satoshi',
})

// Premium serif font for elegant titles (Migra proxy)
const migra = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-migra',
  style: ['normal', 'italic'],
})

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://12img.com'

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: '12img — Minimal Photo Gallery Delivery for Photographers',
    template: '%s | 12img',
  },
  description: 'Beautiful, minimal gallery delivery for professional photographers. Share photo galleries with clients in seconds. No ads, no clutter — just your work, beautifully presented.',
  keywords: [
    'photo gallery',
    'photographer gallery',
    'client gallery',
    'photo delivery',
    'wedding photography',
    'portrait photography',
    'photography portfolio',
    'image sharing',
    'photo sharing platform',
    'photographer tools',
    'client proofing',
    'gallery delivery',
  ],
  authors: [{ name: '12img' }],
  creator: '12img',
  publisher: '12img',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: '/favicon.svg',
    apple: '/logo.svg',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: '12img',
    title: '12img — Minimal Photo Gallery Delivery for Photographers',
    description: 'Beautiful, minimal gallery delivery for professional photographers. Share photo galleries with clients in seconds.',
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: '12img — Minimal Photo Gallery Delivery',
    description: 'Beautiful, minimal gallery delivery for professional photographers. Share photo galleries with clients in seconds.',
    // Twitter image auto-generated by app/opengraph-image.tsx
    creator: '@12img',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    // Add your verification codes here when you have them
    // google: 'your-google-verification-code',
    // yandex: 'your-yandex-verification-code',
  },
  alternates: {
    canonical: siteUrl,
  },
}

const clerkAppearance = {
  variables: {
    colorPrimary: '#212121',
    colorBackground: '#FFFFFF',
    colorInputBackground: '#FFFFFF',
    colorInputText: '#1C1C1C',
    colorText: '#1C1C1C',
    colorTextSecondary: '#6D6D6D',
    colorNeutral: '#1C1C1C',
    colorTextOnPrimaryBackground: '#FFFFFF',
    borderRadius: '12px',
    fontFamily: 'Satoshi, system-ui, sans-serif',
    spacingUnit: '16px',
  },
  elements: {
    card: {
      boxShadow: '0px 10px 36px rgba(0,0,0,0.09)',
      borderRadius: '24px',
      border: 'none',
    },
    socialButtonsBlockButton: {
      backgroundColor: '#FFFFFF',
      border: '1px solid #E5E5E5',
      borderRadius: '12px',
      '&:hover': {
        backgroundColor: '#F9F9F9',
      },
    },
    formFieldInput: {
      backgroundColor: '#FFFFFF',
      border: '1px solid #E5E5E5',
      borderRadius: '12px',
      '&:focus': {
        borderColor: '#212121',
        boxShadow: '0 0 0 1px #212121',
      },
    },
    formButtonPrimary: {
      backgroundColor: '#212121',
      borderRadius: '12px',
      boxShadow: '0px 4px 18px rgba(0,0,0,0.06)',
      '&:hover': {
        backgroundColor: '#3a3a3a',
      },
    },
    footerActionLink: {
      color: '#212121',
      fontWeight: '500',
    },
    badge: {
      display: 'none',
    },
    footer: {
      display: 'none',
    },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={clerkAppearance}>
      <html lang="en">
        <head>
          <link href="https://api.fontshare.com/v2/css?f[]=satoshi@900,700,500,301,701,300,501,401,901,400&display=swap" rel="stylesheet" />
          <OrganizationJsonLd
            name="12img"
            url={siteUrl}
            logo={`${siteUrl}/logo.svg`}
            description="Minimal photo gallery delivery for professional photographers"
          />
          <SoftwareApplicationJsonLd
            name="12img"
            description="Beautiful, minimal gallery delivery for professional photographers. Share photo galleries with clients in seconds."
            url={siteUrl}
            applicationCategory="Photography"
            operatingSystem="Web"
            offers={{ price: '0', priceCurrency: 'USD' }}
          />
        </head>
        <body className={`${migra.variable} font-sans antialiased`}>
          <AuthModalProvider>
            {children}
            <Footer />
            <SupportWidget />
          </AuthModalProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
